# Auto-Fix Bot Configuration File
# 項目配置文件

version: "1.0"
project:
  name: "slasolve"
  description: "SLA Solve - Auto-Fix Bot Integration"
  language: "multi-language"
  repository: "https://github.com/we-can-fix/slasolve"

# 基本設置
settings:
  enabled: true
  auto_fix: true
  auto_commit: false
  create_pr: true
  branch_prefix: "auto-fix/"
  
# 分析配置
analysis:
  enabled: true
  
  # 分析規則
  rules:
    - name: "complexity"
      enabled: true
      threshold: 10
      
    - name: "security"
      enabled: true
      severity: ["critical", "high", "medium"]
      
    - name: "performance"
      enabled: true
      check_algorithms: true
      check_memory: true
      
    - name: "style"
      enabled: true
      enforce_standard: true
      
    - name: "documentation"
      enabled: true
      require_docstrings: true
      
  # 排除路徑
  exclude:
    - "node_modules/"
    - "dist/"
    - "build/"
    - "*.min.js"
    - "*.zip"
    - ".git/"
    
  # 文件類型
  include:
    - "*.js"
    - "*.ts"
    - "*.py"
    - "*.java"
    - "*.go"
    - "*.rs"
    - "*.cpp"
    - "*.c"
    - "*.cs"
    - "*.rb"
    - "*.php"

# 修復配置
fix:
  enabled: true
  
  # 自動修復類型
  auto_fix_types:
    - "syntax_errors"
    - "import_errors"
    - "format_issues"
    - "simple_logic_errors"
    
  # 修復策略
  strategy:
    conservative: false  # 保守模式，只修復確定的問題
    aggressive: true    # 積極模式，嘗試修復更多問題
    
  # 測試驗證
  verify_with_tests: true
  run_tests_after_fix: true
  
  # PR 設置
  pull_request:
    enabled: true
    title_prefix: "[Auto-Fix]"
    add_labels: ["auto-fix", "bot"]
    assign_reviewers: true
    reviewers: []

# 性能優化
optimization:
  enabled: true
  
  areas:
    - "algorithms"
    - "memory_usage"
    - "database_queries"
    - "network_calls"
    - "concurrency"
    
  suggestions_only: false  # false 表示自動應用優化

# 安全掃描
security:
  enabled: true
  
  # 掃描類型
  scan_types:
    - "sql_injection"
    - "xss"
    - "csrf"
    - "sensitive_data"
    - "dependency_vulnerabilities"
    
  # 嚴重程度
  severity_threshold: "medium"  # low, medium, high, critical
  
  # 依賴掃描
  dependency_scan:
    enabled: true
    check_npm: true
    check_pip: true
    check_maven: true
    check_cargo: true

# 代碼質量
code_quality:
  enabled: true
  
  # 質量指標
  metrics:
    - "cyclomatic_complexity"
    - "maintainability_index"
    - "code_duplication"
    - "test_coverage"
    
  # 質量門檻
  thresholds:
    complexity: 10
    duplication: 5  # 百分比
    test_coverage: 80  # 百分比
    maintainability: 65  # 分數

# 測試配置
testing:
  enabled: true
  
  # 測試框架
  frameworks:
    javascript: "jest"
    python: "pytest"
    java: "junit"
    go: "testing"
    
  # 自動生成測試
  auto_generate: false
  
  # 測試覆蓋率
  coverage:
    enabled: true
    target: 80
    fail_under: 60

# 文檔生成
documentation:
  enabled: true
  
  # 文檔類型
  types:
    - "api_docs"
    - "code_comments"
    - "readme"
    
  # 文檔格式
  format: "markdown"
  
  # 自動更新
  auto_update: true

# 通知配置
notifications:
  enabled: true
  
  # Slack 通知
  slack:
    enabled: false
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#auto-fix-bot"
    notify_on:
      - "fix_completed"
      - "security_issue"
      - "pr_created"
      
  # Email 通知
  email:
    enabled: false
    smtp_server: "smtp.example.com"
    smtp_port: 587
    from: "auto-fix-bot@example.com"
    to: []
    notify_on:
      - "security_issue"
      - "critical_error"
      
  # GitHub 通知
  github:
    enabled: true
    notify_on:
      - "pr_created"
      - "fix_completed"

# 雲端委派
cloud_delegation:
  enabled: true
  config_file: "cloud-agent-delegation.yml"
  
  # 任務委派設置
  delegate_tasks:
    - "large_codebase_analysis"
    - "batch_fixes"
    - "comprehensive_security_scan"
    
  # 並行處理
  parallel_processing:
    enabled: true
    max_workers: 10

# 集成配置
integrations:
  # GitHub
  github:
    enabled: true
    token: "${GITHUB_TOKEN}"
    
  # GitLab
  gitlab:
    enabled: false
    token: "${GITLAB_TOKEN}"
    
  # Bitbucket
  bitbucket:
    enabled: false
    username: "${BITBUCKET_USERNAME}"
    password: "${BITBUCKET_PASSWORD}"
    
  # JIRA
  jira:
    enabled: false
    url: "https://your-domain.atlassian.net"
    username: "${JIRA_USERNAME}"
    api_token: "${JIRA_API_TOKEN}"

# 日誌配置
logging:
  enabled: true
  level: "info"  # debug, info, warn, error
  format: "json"
  output: "stdout"
  
  # 日誌文件
  file:
    enabled: true
    path: "./logs/auto-fix-bot.log"
    max_size: "10MB"
    max_files: 5
    rotation: "daily"

# 緩存配置
cache:
  enabled: true
  type: "file"  # file, redis, memory
  ttl: 3600  # 秒
  path: "./.auto-fix-bot-cache"

# 高級配置
advanced:
  # 並發限制
  concurrency:
    max_parallel_tasks: 5
    max_parallel_files: 10
    
  # 超時設置
  timeouts:
    analysis: 300  # 秒
    fix: 180
    test: 300
    
  # 重試策略
  retry:
    enabled: true
    max_attempts: 3
    backoff: "exponential"
    
  # 性能調優
  performance:
    use_cache: true
    incremental_analysis: true
    parallel_processing: true

# 實驗性功能
experimental:
  # AI 輔助修復
  ai_assisted_fixes:
    enabled: false
    model: "gpt-4"
    
  # 預測性分析
  predictive_analysis:
    enabled: false
    
  # 自動重構
  auto_refactoring:
    enabled: false

# 自定義規則
custom_rules:
  enabled: true
  rules_directory: "./.auto-fix-bot/rules"

# 插件配置
plugins:
  enabled: true
  plugins_directory: "./.auto-fix-bot/plugins"
  
  # 已啟用的插件
  active_plugins: []

# 報告配置
reporting:
  enabled: true
  
  # 報告格式
  formats:
    - "html"
    - "json"
    - "markdown"
    
  # 報告輸出
  output_directory: "./reports"
  
  # 報告內容
  include:
    - "analysis_summary"
    - "fixes_applied"
    - "security_issues"
    - "performance_metrics"
    - "code_quality_metrics"

# 環境變量
environment:
  development:
    auto_fix: false
    verbose: true
    
  staging:
    auto_fix: true
    create_pr: true
    
  production:
    auto_fix: true
    create_pr: true
    notify_on_error: true
